name: UNIT-TESTS

on:
    push:
        branches:
            - "master"
            - "develop"
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    unit:
        name: UNIT (API, CRYPTO, TRANSACTIONS)
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [ 24 ]

        steps:
            - uses: actions/checkout@v7

            - uses: pnpm/action-setup@v4

            - name: Use Node.js 24
              uses: actions/setup-node@v7
              with:
                  node-version: 24
                  cache: pnpm

            - name: Install And Build
              run: pnpm install --frozen-lockfile && pnpm build

            - name: NAMESERVICE-CRYPTO
              run: |
                  cd packages/nameservice-crypto
                  pnpm run test:unit:coverage --maxWorkers=2

            - uses: codecov/codecov-action@v5
              with:
                  directory: packages/nameservice-crypto/.coverage
                  flags: nameservice-crypto

            - name: NAMESERVICE-TRANSACTIONS
              run: |
                  cd packages/nameservice-transactions
                  pnpm run test:unit:coverage --maxWorkers=2

            - uses: codecov/codecov-action@v5
              with:
                  directory: packages/nameservice-transactions/.coverage
                  flags: nameservice-transactions

            - name: NAMESERVICE-API
              run: |
                  cd packages/nameservice-api
                  pnpm run test:unit:coverage --maxWorkers=2

            - uses: codecov/codecov-action@v5
              with:
                  directory: packages/nameservice-api/.coverage
                  flags: nameservice-api
