name: UNIT-TESTS

on:
    push:
        branches:
            - "master"
            - "develop"
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    unit:
        name: UNIT (API, CRYPTO, TRANSACTIONS)
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install And Build
              run: yarn && yarn build

            - name: NAMESERVICE-CRYPTO
              run: cd packages/nameservice-crypto && yarn test:unit:coverage --coverageDirectory .coverage/unit-nameservice-crypto --maxWorkers=2

            - uses: codecov/codecov-action@v2
              with:
                  files: .coverage/unit-nameservice-crypto/lcov.info
                  flags: nameservice-crypto
                  verbose: true

            - name: NAMESERVICE-TRANSACTIONS
              run: cd packages/nameservice-transactions && yarn test:unit:coverage --coverageDirectory .coverage/unit-nameservice-transactions --maxWorkers=2

            - uses: codecov/codecov-action@v2
              with:
                files: .coverage/unit-nameservice-transactions/lcov.info
                flags: nameservice-transactions
                verbose: true

            - name: NAMESERVICE-API
              run: cd packages/nameservice-api && yarn test:unit:coverage --coverageDirectory .coverage/unit-nameservice-api --maxWorkers=2

            - uses: codecov/codecov-action@v2
              with:
                files: .coverage/unit-nameservice-api/lcov.info
                flags: nameservice-api
                verbose: true
